import type { Timestamp } from 'firebase-admin/firestore';
import type { ElasticDocument } from '../elastic/elastic.types';
import type { I18nField } from '../shared/types';

/**
 * What a piece of equipment is for.
 *
 * The app's shelf groups tools and glassware together but files ice with the
 * ice ingredients, so the distinction has to survive the round trip rather
 * than being inferred from the title. Pre-Flow-04 documents carry no kind at
 * all and read back as {@link EQUIPMENT_KINDS.TOOL}.
 */
export const EQUIPMENT_KINDS = {
  TOOL: 'tool',
  GLASSWARE: 'glassware',
  ICE: 'ice',
} as const;

export type EquipmentKind = typeof EQUIPMENT_KINDS[keyof typeof EQUIPMENT_KINDS];

/**
 * Equipment Domain Model
 * 
 * Represents a piece of equipment used in cocktail preparation.
 * Following DDD principles, this is the core entity of the Equipment domain.
 */
export interface Equipment {
  /** Unique identifier (Firebase document ID) */
  id: string;
  
  /** The name/title of the equipment (translatable) */
  title: I18nField;

  /** Google Cloud Storage path or URL to the equipment image */
  image?: string | null;

  /**
   * Stable human key -- "shaker", "coupe". Mirrors `Ingredient.slug`: the
   * shelf is collected on first run before any account exists, so it is stored
   * as slugs rather than document ids, and this is what lets a shaker picked
   * during onboarding resolve to a real document later.
   */
  slug?: string | null;

  /** Tool, glassware or ice. Absent on the pre-Flow-04 catalogue. */
  kind?: EquipmentKind | null;

  /**
   * Catalogue-wide "in N drinks" figure shown on the bar's item sheet.
   * Derived -- see the catalogue stats module -- never authored by hand.
   */
  cocktailCount?: number | null;
  
  /** Timestamp when the equipment was created */
  createdAt?: string;
  
  /** Timestamp when the equipment was last updated */
  updatedAt?: string;
}

export interface EquipmentDocument extends Omit<Equipment, 'id' | 'createdAt' | 'updatedAt'> {
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

/**
 * Data transfer object for creating a new equipment
 * Excludes ID and timestamps as they are generated by the system
 */
export interface CreateEquipmentDto {
  title: I18nField;
  image?: string | null;
  slug?: string | null;
  kind?: EquipmentKind | null;
}

/**
 * Data transfer object for updating an existing equipment
 * All fields are optional to support partial updates
 */
export interface UpdateEquipmentDto {
  id: string;
  title?: I18nField;
  image?: string | null;
  slug?: string | null;
  kind?: EquipmentKind | null;
}

export interface EquipmentSearchDocument extends ElasticDocument, Omit<Equipment, 'createdAt' | 'updatedAt'> {}
