/**
 * Equipment Domain Model
 * 
 * Represents a piece of equipment used in cocktail preparation.
 * Following DDD principles, this is the core entity of the Equipment domain.
 */
export interface Equipment {
  /** Unique identifier (Firebase document ID) */
  id: string;
  
  /** The name/title of the equipment */
  title: string;
  
  /** Timestamp when the equipment was created */
  createdAt?: Date;
  
  /** Timestamp when the equipment was last updated */
  updatedAt?: Date;
}

/**
 * Data transfer object for creating a new equipment
 * Excludes ID and timestamps as they are generated by the system
 */
export interface CreateEquipmentDto {
  title: string;
}

/**
 * Data transfer object for updating an existing equipment
 * All fields are optional to support partial updates
 */
export interface UpdateEquipmentDto {
  title?: string;
}
