import { Timestamp } from 'firebase-admin/firestore';
import type { ElasticDocument } from '../elastic/elastic.types';
import { I18nField } from '../shared/types';

/**
 * Equipment Domain Model
 * 
 * Represents a piece of equipment used in cocktail preparation.
 * Following DDD principles, this is the core entity of the Equipment domain.
 */
export interface Equipment {
  /** Unique identifier (Firebase document ID) */
  id: string;
  
  /** The name/title of the equipment (translatable) */
  title: I18nField;

  /** Google Cloud Storage path or URL to the equipment image */
  image?: string;
  
  /** Timestamp when the equipment was created */
  createdAt?: string;
  
  /** Timestamp when the equipment was last updated */
  updatedAt?: string;
}

export interface EquipmentDocument extends Omit<Equipment, 'id' | 'createdAt' | 'updatedAt'> {
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

/**
 * Data transfer object for creating a new equipment
 * Excludes ID and timestamps as they are generated by the system
 */
export interface CreateEquipmentDto {
  title: I18nField;
  image?: string;
}

/**
 * Data transfer object for updating an existing equipment
 * All fields are optional to support partial updates
 */
export interface UpdateEquipmentDto {
  id: string;
  title?: I18nField;
  image?: string;
}

export interface EquipmentSearchDocument extends ElasticDocument, Omit<Equipment, 'createdAt' | 'updatedAt'> {}
