/**
 * Common ingredient categories for validation
 */
export const INGREDIENT_CATEGORIES = {
  SPIRIT: 'spirit',
  LIQUEUR: 'liqueur', 
  MIXER: 'mixer',
  SYRUP: 'syrup',
  BITTERS: 'bitters',
  GARNISH: 'garnish',
  FRUIT: 'fruit',
  HERB: 'herb',
  SPICE: 'spice',
  OTHER: 'other'
} as const;

export type IngredientCategory = typeof INGREDIENT_CATEGORIES[keyof typeof INGREDIENT_CATEGORIES];

/**
 * Ingredient Domain Model
 * 
 * Represents a basic ingredient used in cocktail recipes.
 * Following DDD principles, this is the core entity of the Ingredient domain.
 */
export interface Ingredient {
  /** Unique identifier (Firebase document ID) */
  id: string;
  
  /** The name/title of the ingredient */
  title: string;
  
  /** Category of the ingredient (e.g., "spirit", "mixer", "garnish", "liqueur") */
  category: IngredientCategory;

  /** Google Cloud Storage path or URL to the ingredient image */
  image?: string;
  
  /** Timestamp when the ingredient was created */
  createdAt?: Date;
  
  /** Timestamp when the ingredient was last updated */
  updatedAt?: Date;
}

/**
 * Data transfer object for creating a new ingredient
 * Excludes ID and timestamps as they are generated by the system
 */
export interface CreateIngredientDto {
  title: string;
  category: IngredientCategory;
  image?: string;
}

/**
 * Data transfer object for updating an existing ingredient
 * All fields are optional to support partial updates
 */
export interface UpdateIngredientDto {
  title?: string;
  category?: IngredientCategory;
  image?: string;
}
