import type { Timestamp } from 'firebase-admin/firestore';
import type { ElasticDocument } from '../elastic/elastic.types';
import type { I18nField } from '../shared/types';

/**
 * Common ingredient categories for validation
 */
export const INGREDIENT_CATEGORIES = {
  SPIRIT: 'spirit',
  LIQUEUR: 'liqueur', 
  MIXER: 'mixer',
  SYRUP: 'syrup',
  BITTERS: 'bitters',
  GARNISH: 'garnish',
  FRUIT: 'fruit',
  HERB: 'herb',
  SPICE: 'spice',
  ICE: 'ice',
  OTHER: 'other'
} as const;

export type IngredientCategory = typeof INGREDIENT_CATEGORIES[keyof typeof INGREDIENT_CATEGORIES];

/**
 * Ingredient Domain Model
 * 
 * Represents a basic ingredient used in cocktail recipes.
 * Following DDD principles, this is the core entity of the Ingredient domain.
 */
export interface Ingredient {
  /** Unique identifier (Firebase document ID) */
  id: string;
  
  /** The name/title of the ingredient */
  title: I18nField;
  
  /** Category of the ingredient (e.g., "spirit", "mixer", "garnish", "liqueur") */
  category: IngredientCategory;

  /** Google Cloud Storage path or URL to the ingredient image */
  image?: string | null;

  /**
   * Stable human key -- "gin", "sweetVermouth", "lime".
   *
   * The shelf is collected on the first run before any account exists, so it
   * is stored as slugs rather than document ids. This is what lets that
   * on-device shelf resolve to real ingredient documents later.
   */
  slug?: string | null;

  /**
   * How many drinks adding this one bottle would make pourable for a typical
   * shelf. Denormalized -- it is what "add lime, unlocks 11 more" and the
   * near-miss list on zero results are ranked by.
   */
  unlocks?: number | null;

  /**
   * Catalogue-wide "in N drinks" figure shown on the bar's item sheet.
   * Derived alongside {@link Ingredient.unlocks} -- never authored by hand.
   */
  cocktailCount?: number | null;

  /** Timestamp when the ingredient was created */
  createdAt?: string;
  
  /** Timestamp when the ingredient was last updated */
  updatedAt?: string;
}

/**
 * Data transfer object for creating a new ingredient
 * Excludes ID and timestamps as they are generated by the system
 */
export interface CreateIngredientDto {
  title: I18nField;
  category: IngredientCategory;
  image?: string | null; // null indicates removal of the image
  slug?: string | null;
}

/**
 * Data transfer object for updating an existing ingredient
 * All fields are optional to support partial updates
 */
export interface UpdateIngredientDto {
  id: string;
  title?: I18nField;
  category?: IngredientCategory;
  image?: string | null; // null indicates removal of the image
  slug?: string | null;
  unlocks?: number | null;
  cocktailCount?: number | null;
}

/**
 * Firestore document representation of an Ingredient
 *
 * Uses I18nField for title to support multiple languages
 * Timestamps are stored as Firestore Timestamps
 */
export interface IngredientDocument extends Omit<Ingredient, 'id' | 'createdAt' | 'updatedAt'> {

  createdAt: Timestamp;

  updatedAt: Timestamp;
}

export interface IngredientSearchDocument extends ElasticDocument, Omit<Ingredient, 'createdAt' | 'updatedAt'> {}
