import 'package:cloud_firestore/cloud_firestore.dart';
import 'shared_types.dart';

/// Common ingredient categories for validation
enum IngredientCategory {
  spirit,
  liqueur,
  mixer,
  syrup,
  bitters,
  garnish,
  fruit,
  herb,
  spice,
  other,
}

/// Ingredient Domain Model (UI/Business Logic Layer)
///
/// Represents a basic ingredient used in cocktail recipes.
/// This is a clean domain entity with translated strings for the UI layer.
/// Following DDD principles, this is the core entity of the Ingredient domain.
class Ingredient {
  /// Unique identifier (Firebase document ID)
  final String id;

  /// The name/title of the ingredient (already translated)
  final String title;

  /// Category of the ingredient (e.g., "spirit", "mixer", "garnish", "liqueur")
  final IngredientCategory category;

  /// Google Cloud Storage path or URL to the ingredient image
  final String? image;

  /// Timestamp when the ingredient was created
  final DateTime? createdAt;

  /// Timestamp when the ingredient was last updated
  final DateTime? updatedAt;

  const Ingredient({
    required this.id,
    required this.title,
    required this.category,
    this.image,
    this.createdAt,
    this.updatedAt,
  });

  Ingredient copyWith({
    String? id,
    String? title,
    IngredientCategory? category,
    String? image,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Ingredient(
      id: id ?? this.id,
      title: title ?? this.title,
      category: category ?? this.category,
      image: image ?? this.image,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}

/// Firestore Document representation of an Ingredient
///
/// Uses I18nField for title to support multiple languages
/// Timestamps are stored as Firestore Timestamps
class IngredientDocument {
  /// I18n field containing translations for the ingredient title
  final I18nField title;

  /// Category of the ingredient
  final IngredientCategory category;

  /// Google Cloud Storage path or URL to the ingredient image
  final String? image;

  /// Firestore Timestamp when the ingredient was created
  final Timestamp createdAt;

  /// Firestore Timestamp when the ingredient was last updated
  final Timestamp updatedAt;

  const IngredientDocument({
    required this.title,
    required this.category,
    this.image,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Convert Firestore document to IngredientDocument
  factory IngredientDocument.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return IngredientDocument.fromMap(data);
  }

  factory IngredientDocument.fromMap(Map<String, dynamic> map) {
    return IngredientDocument(
      title: Map<String, String>.from(map['title'] ?? {}),
      category: IngredientCategory.values.firstWhere(
        (e) => e.name == map['category'],
        orElse: () => IngredientCategory.other,
      ),
      image: map['image'],
      createdAt: map['createdAt'] as Timestamp,
      updatedAt: map['updatedAt'] as Timestamp,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'category': category.name,
      'image': image,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
    };
  }
}

/// Transformer to convert between IngredientDocument and Ingredient entity
class IngredientTransformer
    extends FirestoreTransformer<IngredientDocument, Ingredient> {
  @override
  Ingredient fromDocument(
    IngredientDocument document,
    String id,
    SupportedLocale locale,
  ) {
    return Ingredient(
      id: id,
      title: document.title.translate(locale),
      category: document.category,
      image: document.image,
      createdAt: document.createdAt.toDate(),
      updatedAt: document.updatedAt.toDate(),
    );
  }

  @override
  IngredientDocument toDocument(Ingredient entity) {
    // When creating/updating, you'd typically provide the I18n fields
    // This is a simplified version
    throw UnimplementedError(
      'Use CreateIngredientDto or UpdateIngredientDto for writes',
    );
  }

  /// Convert Firestore DocumentSnapshot directly to Ingredient entity
  Ingredient fromFirestore(DocumentSnapshot doc, SupportedLocale locale) {
    final document = IngredientDocument.fromFirestore(doc);
    return fromDocument(document, doc.id, locale);
  }
}

/// Data transfer object for creating a new ingredient
/// Excludes ID and timestamps as they are generated by the system
class CreateIngredientDto {
  final String title;
  final IngredientCategory category;
  final String? image;

  const CreateIngredientDto({
    required this.title,
    required this.category,
    this.image,
  });

  Map<String, dynamic> toMap() {
    return {'title': title, 'category': category.name, 'image': image};
  }
}

/// Data transfer object for updating an existing ingredient
/// All fields are optional to support partial updates
class UpdateIngredientDto {
  final String? title;
  final IngredientCategory? category;
  final String? image;

  const UpdateIngredientDto({this.title, this.category, this.image});

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    if (title != null) map['title'] = title;
    if (category != null) map['category'] = category!.name;
    if (image != null) map['image'] = image;
    return map;
  }
}
