// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClgbjWswnmSnKNcmgIyJ8KUHM0KAuy6Ao',
    appId: '1:768164532049:android:3fd918eef7c7f010f04d70',
    messagingSenderId: '768164532049',
    projectId: 'party-bar',
    storageBucket: 'party-bar.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvtCBZIbwpffCKAkCcaoN8UjlfcPSuXbw',
    appId: '1:768164532049:ios:d74856cd12da65d6f04d70',
    messagingSenderId: '768164532049',
    projectId: 'party-bar',
    storageBucket: 'party-bar.firebasestorage.app',
    androidClientId: '768164532049-78gpucmn2hspbup033qi4kiqqp70ubtm.apps.googleusercontent.com',
    iosClientId: '768164532049-5a25p820maf1018a71ddtpfmvdnkf2bd.apps.googleusercontent.com',
    iosBundleId: 'com.partyBar.debug',
  );
}
